### PR TITLE
Fixes #18

### LINKED ISSUE #18: Unable to use this role if /usr/local is not empty
I encountered this problem when I was trying to run `mac-dev-playbook`. Before running the playbook, I installed ansible using pip. This role fails to clone the homebrew repo if /usr/local is not empty.

As a workaround, I installed homebrew manually, then re-ran the playbook.

### PR DESCRIPTION
**Pull request by scottrigby**
Quick PR for #18. 

Also see: https://github.com/Homebrew/legacy-homebrew/issues/41690#issuecomment-121282158 and https://github.com/Homebrew/legacy-homebrew/pull/45934.

Note that ATM I'm not easily able to test modifying `ansible-role-homebrew` since I'm including it as a role via https://github.com/geerlingguy/mac-dev-playbook.

### CODE REVIEW

**Comment by tcr-ableton** [comment]
I confirm this fixes #18 for me.
Running El Capitan.
👍

**Comment by tcr-ableton** [comment]
Does not fix #18 issue for me.
Running El Capitan. 

Still getting `msg": "fatal: destination path '/usr/local' already exists and is not an empty directory."`

**Comment by ksylvan** [comment]
You can also use the `file` module with `owner` instead of doing a shell chown.

**Comment by geerlingguy** [comment]
And this is a little more heavy-handed than I like to set things in my roles (`sudo chown -R $(USER):admin /usr/local`) — there are some cases where people may want slightly different ownership that still works with Homebrew, and I'd rather not limit them to all $USER:admin...

Going to see if #30 solves the problem in a slightly more efficient/less intrusive manner.

**Pull request closed without merging**
