### PR TITLE
Add support for uninstalling cask apps

### PR DESCRIPTION
**Pull request by bartoszj**
Added support for uninstalling cask applications.

### CODE REVIEW

**Comment by holms** [comment]
@geerlingguy could this be merged please :)?

**Comment by daften** [comment]
Agreed with @holms , commits and PR's should be focused around one thing!

**Comment by elliotweiser** [comment]
Agreed. Any participants on this thread who'd like to cut a new PR for the High Sierra permissions, fix please go ahead, and I'll review that first. Uninstalling casks can come next.

**Comment by bartoszj** [comment]
@holms @daften @elliotweiser 
Done. I've moved High Sierra fix to another PR.

**Pull request merged**
