### PR TITLE
Add install options to packages

### PR DESCRIPTION
**Pull request by imjoshholloway**
This resolves https://github.com/geerlingguy/ansible-role-homebrew/issues/31 by allowing you to specify a dict of packages and options in the variables whilst maintaining backward compatibility:

``` yaml
...

homebrew_installed_packages:
  - vim

homebrew_package_options:
  vim:
    - with-lua
    - with-luajit

...
```

### CODE REVIEW

**Comment by autoferrit** [comment]
Are there any plans on getting this merged in? Or any updates?

**Comment by autoferrit** [comment]
I think, to fix this, there just needs to be a new line:

```yaml
homebrew_package_options:
```

making the final file look like:

```yaml
---
homebrew_install_path: /usr/local
homebrew_brew_bin_path: /usr/local/bin

homebrew_installed_packages:
  - ssh-copy-id
  - pv

homebrew_package_options:

homebrew_upgrade_all_packages: no

homebrew_taps:
  - caskroom/cask

homebrew_cask_apps:
  - firefox

homebrew_cask_appdir: /Applications

homebrew_use_brewfile: true
homebrew_brewfile_dir: '~
```

This change makes it work locally.

**Comment by oxyc** [comment]
How about

```
# Brew.
- name: Ensure configured homebrew packages are installed.
  homebrew:
    name: "{{ item.name|default(item) }}"
    install_options: "{{ item.install_options|default(omit) }}"
    state: "{{ item.state|default('present') }}"
  with_items: "{{ homebrew_installed_packages }}"
```

**Comment by geerlingguy** [comment]
@oxyc - I like that suggestion... and it would probably also be nice to do that for the `geerlingguy.nodejs` role which uses a similar structure.

If it were set up like that, I would be happy to merge.

**Comment by oxyc** [comment]
@geerlingguy I already opened up a PR :) #33

**Comment by geerlingguy** [comment]
Closing in favor of #69 – that method feels a little more clean and expands the existing functionality an a slightly simpler way.

**Pull request closed without merging**
