### PR TITLE
Allow homebrew folders to be customized

### PR DESCRIPTION
**Pull request by tsterker**
An alternative proposal to #124 to address the issue of missing folder permission in certain circumstances.

### CODE REVIEW

**Comment by elliotweiser** [comment]
Makes sense, however I can imagine customizing this force the user to have to redefine a whole bunch of paths that are otherwise standard. Maybe the bulk of these can move to `vars/main.yml` and extra paths can be added with the variable in `defaults/main.yml`?

**Comment by elliotweiser** [comment]
I'll make sure this change is released later today.

**Comment by tsterker** [comment]
@elliotweiser Is there a plan to tag this change? Currently I'm using `version: master` in my requirements.

**Comment by elliotweiser** [comment]
@tsterker Just released in 3.1.0

**Pull request merged**
