### PR TITLE
Support check mode by forcing var registration

### PR DESCRIPTION
**Pull request by proinsias**

### CODE REVIEW

**Comment by geerlingguy** [comment]
👍

**Comment by geerlingguy** [comment]
This is in the 2.6.1 release. Sorry about that, it's slightly harder to automatically check check mode in the Mac test environment (but might be good to do that sometime).

**Comment by elliotweiser** [comment]
This might have some mixed results. The `brew --cache` step won't necessarily work properly if `brew` isn't installed to begin with (subsequent executions will probably work though).

**Comment by geerlingguy** [comment]
I'd imagine it should work fine though if you're running it after you've already run the role once. I usually use it to ensure my system's in the same state it was yesterday, or just when validating an update, that sort of thing

**Pull request merged**
