### PR TITLE
Fixes #45: Agree to Apple Xcode license agreements in Homebrew setup.

### LINKED ISSUE #45: Ensure Homebrew is installed: NoneType object has no attribute version
Just trying to get started installing homebrew on macOS Sierra 10.12.1 with this play:

    - name: Install brew
      hosts: all_osx_hosts
      vars:
        homebrew_installed_packages:
          - ant
          - cmake
          - jq
      roles:
        - geerlingguy.homebrew
      tags:
        - debug

This fails with

    Traceback (most recent call last):
      File "/var/folders/jm/3n8_ksbs4fz49dlz_mlchtgw0000gn/T/ansible_HPa4di/ansible_module_git.py", line 1040, in <module>
        main()
      File "/var/folders/jm/3n8_ksbs4fz49dlz_mlchtgw0000gn/T/ansible_HPa4di/ansible_module_git.py", line 923, in main
        if depth is not None and git_version_used < LooseVersion(1.9.1):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/version.py", line 296, in __cmp__
        return cmp(self.version, other.version)
    AttributeError: NoneType object has no attribute version

at which point I don't even know where to being looking for the cause.

How can I get this work ?

### PR DESCRIPTION
**Pull request by z00m1n**
Tested to work OK on setup described at https://github.com/geerlingguy/ansible-role-homebrew/issues/45 with target machine reset to snapshot taken right after initial installation.

### CODE REVIEW

**Comment by z00m1n** [comment]
Sorry for sending all my changes in a single pull request. If someone could let me know how to split up multiple commits into multiple pull requests, I'd be most grateful.

**Comment by z00m1n** [comment]
The [pull request Travis check](https://travis-ci.org/geerlingguy/ansible-role-homebrew/builds/183268240) fails with

    /Users/travis/build.sh: line 148: shell_session_update: command not found

I don't know what to do about that.

**Comment by geerlingguy** [comment]
To split to multiple PR's, you'd need a branch per change (then you can submit a PR per branch). If you can do that, please do so, and that way I can merge in the defaults changes separately (since that's a lot simpler/easier to test :)

**Comment by z00m1n** [comment]
closing this pull request, will open one per issue

**Pull request closed without merging**
