### PR TITLE
Put install tasks for cask before brew to fix dependencies on Java

### PR DESCRIPTION
**Pull request by matthewcosgrove**
For Java devs this is a fundamental set up. Maven is a core Java build tool, and would be standard in most set ups. Java is provided as a cask and needs to be installed prior to brew install on any packages which run on Java. 

8e694635-4126-4d78-a3f2-d6d6ddee05ab

Those who do not use Maven would likely use Gradle

3ee5199a-4605-428a-b0a2-b5d11adc4636

This also affects installs such as [elastic search](http://www.inanzzz.com/index.php/post/wv82/solution-for-elasticsearch-java-is-required-to-install-this-formula-in-mac-os)

### CODE REVIEW

**Comment by elliotweiser** [comment]
Just for my own sanity, is it possible that there are casks with dependencies on standard homebrew packages?

**Comment by geerlingguy** [comment]
Echoing @elliotweiser's statement... I think the reason I stuck Casks in after Packages was because it makes more sense (logically) for packages the be the bedrock/foundation, and Casks would be software that may depend on the packages.

It seems really strange to me that java is a cask and not a package—AFAIK, all other languages are packages (php, ruby, python, go, rust, etc.). Why is Java a special snowflake?

**Comment by elliotweiser** [comment]
Unfortunately this isn't anything new. Installing Java on Mac OS X has been a non-standard process for years.  It doesn't explain why it was packaged as a cask rather than a formula, but I guess I'm not surprised.

**Comment by elliotweiser** [comment]
@matthewcosgrove Does this fix #38?

**Comment by matthewcosgrove** [comment]
Yes I definitely see it's logical to put casks after brew, especially when cask is branded as an extension of homebrew. However, in reality they are independent projects with different goals. 

The main distinction to make between them for this PR is that casks are pre-compiled binaries and therefore, as I understand it, should not depend on any homebrew packages. In contrast `brew install` may compile or just download pre-compiled binaries. (a relevant discussion is here:  https://github.com/caskroom/homebrew-cask/issues/7002)

@elliotweiser yes this does fix #38

**Comment by matthewcosgrove** [comment]
According to this, at the time of writing, there are currently 166 homebrew formulae that depend on Java http://brewformulas.org/Java

**Comment by mdotson** [comment]
@matthewcosgrove do you plan on resolving the merge conflicts here? I'd love to see this go in.

**Comment by elliotweiser** [comment]
@geerlingguy @matthewcosgrove I've resolved the conflicts in this PR to preserve the original intent of the change. This will fix/address the following issues:

https://github.com/geerlingguy/ansible-role-homebrew/issues/38
https://github.com/geerlingguy/mac-dev-playbook/issues/39

**Pull request merged**
